#FROM quay.io/centos-bootc/centos-bootc-dev:stream9
FROM quay.io/centos-bootc/fedora-bootc-dev:eln

RUN dnf install -y httpd mariadb mariadb-server php-fpm php-mysqlnd vim-enhanced && dnf clean all
ADD lamp.local-2023-03-09-0123.sql /var/local/
ADD wp.tgz /var/www/html

ADD wp-setup.service /etc/systemd/system/
ADD --chmod=755 wp-setup.sh /etc
RUN systemctl enable httpd mariadb wp-setup php-fpm
